export const constants = {
    SET_ACCESS : 'set_access_token',
    SET_REFRESH : 'set_refresh_token',
    SET_USER : 'set_user_details',
    SET_TRACKS1 : 'set_tracks_1month',
    SET_TRACKS2 : 'set_tracks_6months',
    SET_TRACKS3 : 'set_tracks_alltime',
    SET_ARTISTS1 : 'set_artists_1month',
    SET_ARTISTS2 : 'set_artists_6months',
    SET_ARTISTS3 : 'set_artists_alltime',
    SET_GENRES1 : 'set_genres_1month',
    SET_GENRES2 : 'set_genres_6months',
    SET_GENRES3 : 'set_genres_alltime',
    SET_RECOMMEND1 : 'set_recommended_tracks',
    SET_RECOMMEND2 : 'set_recommended_artists',
    SET_USERPLAYLISTS : 'set_user_playlists',
    SET_FEATUREDPLAYLISTS : 'set_featured_playlists',
    SET_ARTISTCOUNT : 'set_artists_count',
    SET_FEATURES : 'set_audio_features',
    LOG_OUT : 'user_logged_out'
}